### ISSUE TITLE
IBM Editorial Style Guide Link is Broken

### ISSUE THREAD

**Issue by aucolins** [BolajiAyodeji/awesome-technical-writing#43]
I tried the link for 
IBM Editorial Style Guide
https://www.ibm.com/developerworks/library/styleguidelines/

from the page:
https://github.com/BolajiAyodeji/awesome-technical-writing#style-guides

It appears to be broken.

**Comment by BolajiAyodeji** [comment]
Thanks for reporting this @aucolins. I'd try to find the updated link and revert accordingly.

**Comment by BolajiAyodeji** [comment]
@allcontributors please add @aucolins for bug.
